require("gupteswar.plugins-setup")
require("gupteswar.core.options")
require("gupteswar.core.keymaps")
require("gupteswar.core.colorscheme")
require("gupteswar.plugins.comment")
require("gupteswar.plugins.nvim-tree")
